### ISSUE TITLE
Use on Raspberry Pi?

### ISSUE THREAD

**Issue by mamarais** [ricklamers/gridstudio#60]
Wonderful application!  I would love to use it on a Raspberry Pi for use in education. I have a new Pi 4B with 4GB of RAM. I have the ARM version of Docker installed and it works. I have cloned gridstudio and ran sudo ./run.sh and get a return value of "gridstudio". If if then go to http://127.0.0.1:8080 using Chromium I get a proxy server error. So that is where I got to....

Regards

Mario

**Comment by ricklamers** [comment]
>sudo ./run.sh and get a return value of "gridstudio"

This happens when you have a container called "gridstudio" and it tries to boot it. If you have no critical data in the Grid studio yet - you can destroy the instance by running `sudo ./destroy.sh`.

Run `sudo ./run.sh` after this and see what the output is (and whether you can reach it on 127.0.0.1:8080).

If not, please post the output of `docker logs <CONTAINER>` here.

Also, I would be very interested to learn about how Grid studio could be improved to be more enable for use in an educational environment. Please provide any feedback you have.

**Comment by ricklamers** [comment]
Inactivity close, feel free to re-open.
