### ISSUE TITLE
Deploy on windows without docker?

### ISSUE THREAD

**Issue by Timothy13Munyao** [ricklamers/gridstudio#74]
Is it deployable on windows without docker or just on docker windows containers?

**Comment by ricklamers** [comment]
@Timothy13Munyao right now the easy way to run Grid Studio is to run it as a Linux Docker container. Either on macOS, Windows or Linux. You could very well run Grid Studio directly on any of these operating systems. But it requires more setup, since you'd need to make sure all required dependencies are installed.

Take a look at the [Dockerfile](https://github.com/ricklamers/gridstudio/blob/master/grid-app/Dockerfile) to get an idea of how to run it locally. If you're on Linux for example, in principle you could run all the commands in the Dockerfile and it would run locally.
