### ISSUE TITLE
Image ricklamers/gridstudio:release

### ISSUE THREAD

**Issue by lijinyang0228** [ricklamers/gridstudio#77]

**Comment by lijinyang0228** [comment]
I read the files about docker, and I have a question. In run.sh, if the container already exists, we run image called ricklamers/gridstudio:release. This seems an existing image. But where is this image? When did I get it? 
I create an image using build.sh according to Dockerfile, right? But in Dockerfile, I didn't find anything about download an existing image called ricklamers/gridstudio.
This is the first time I study with a docker, so maybe I don't have a thorough understanding, and I'm sorry for that.

**Comment by 1kastner** [comment]
If you just run the run.sh, you actually never touch the downloaded source code. Instead, you trust ricklamers that he uploaded a good docker image and you just download the already prepared file.
For a deeper understanding, please read the docker manuals or buy a book about that topic ;-)

**Comment by ricklamers** [comment]
@lijinyang0228 the Docker image referenced in `run.sh` is hosted on the Docker hub. It's an online repository that contains prebuilt Docker images.

Like @1kastner says, when you run the `run.sh` command Docker automatically downloads and executes the Docker image.

However, @1kastner it does actually use the downloaded source code if you directly use `run.sh` since it mounts the directory to the Docker image before running the bash script in the Docker image that actually compiles and loads Grid Studio.

**Comment by 1kastner** [comment]
Sorry, here I was imprecise.

**Comment by ricklamers** [comment]
No worries! Love your involvement.
